version: "3"

services:
  web-debug:
    build:
      context: .
      dockerfile: ./debug.Dockerfile
    restart: always
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /key.json
    volumes:
      - .:/app
      # :ro → read only
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/key.json:ro

    expose:
      - "8000"
      - "5678"
    ports:
      - 8000:8000
      - 5678:5678
