version: "3"

services:
  web:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    links:
      - db
    # command: ["./wait-for-mysql.sh", "db", "python", "app.py"]
    depends_on:
      - db

  db:
    image: "mysql:5.7"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: search_laundry_python_development
      # 仮想コンテナにアクセスするためのポート番号
    ports:
      - "3308:3306"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
