"""add user_refresh_token column

Revision ID: 0798f1532954
Revises: 8a294ba4fd06
Create Date: 2022-07-21 05:09:58.528833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0798f1532954'
down_revision = '8a294ba4fd06'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_refresh_token', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_refresh_token')
    # ### end Alembic commands ###
