"""add column in laundry model

Revision ID: 8a294ba4fd06
Revises: e00d49797759
Create Date: 2022-07-18 01:59:51.130425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a294ba4fd06'
down_revision = 'e00d49797759'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laundry', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('laundry', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('laundry', 'deleted_at')
    op.drop_column('laundry', 'is_deleted')
    # ### end Alembic commands ###
