"""initial migration

Revision ID: e00d49797759
Revises: 
Create Date: 2022-07-13 06:53:56.883630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e00d49797759'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laundry',
                    sa.Column('laundry_id', sa.Integer(),
                              nullable=False, autoincrement=True),
                    sa.Column('laundry_name', sa.String(
                        length=255), nullable=False),
                    sa.Column('laundry_address', sa.String(
                        length=255), nullable=False),
                    sa.Column('laundry_opening_date',
                              sa.Date(), nullable=False),
                    sa.Column('laundry_open_time', sa.Time(), nullable=False),
                    sa.Column('laundry_close_time', sa.Time(), nullable=False),
                    sa.Column('laundry_image_name', sa.String(
                        length=255), nullable=True),
                    sa.PrimaryKeyConstraint('laundry_id')
                    )
    op.create_table('user',
                    sa.Column('user_id', sa.Integer(),
                              nullable=False, autoincrement=True),
                    sa.Column('user_nickname', sa.String(
                        length=255), nullable=False),
                    sa.Column('user_mail_address', sa.String(
                        length=255), nullable=False),
                    sa.Column('user_password', sa.String(
                        length=255), nullable=False),
                    sa.PrimaryKeyConstraint('user_id')
                    )
    op.create_table('comment',
                    sa.Column('comment_id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('comment_body', sa.Text(), nullable=False),
                    sa.Column('comment_created_at',
                              sa.DateTime(), nullable=False),
                    sa.Column('comment_user_id', sa.Integer(), nullable=False),
                    sa.Column('comment_laundry_id',
                              sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['comment_laundry_id'], [
                        'laundry.laundry_id'], name='comment__comment_laundry_id_fk', ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['comment_user_id'], [
                        'user.user_id'], name='comment__comment_user_id_fk', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('comment_id')
                    )
    op.create_table('laundry_to_machine_type',
                    sa.Column('laundry_to_machine_type_laundry_id',
                              sa.Integer(), nullable=False),
                    sa.Column('laundry_to_machine_type_machine_type_id', sa.Enum('MACHINE_TYPE_WASHING_MACHINE', 'MACHINE_TYPE_SHOE_WASHING_MACHINE',
                              'MACHINE_TYPE_FUTON_WASHING_MACHINE', 'MACHINE_TYPE_DRYER', name='machinetype'), nullable=False),
                    sa.Column('laundry_to_machine_type_machine_count',
                              sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['laundry_to_machine_type_laundry_id'], [
                        'laundry.laundry_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint(
                        'laundry_to_machine_type_laundry_id', 'laundry_to_machine_type_machine_type_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('laundry_to_machine_type')
    op.drop_table('comment')
    op.drop_table('user')
    op.drop_table('laundry')
    # ### end Alembic commands ###
